sudo: false
language: ruby
script: bundle exec rake ci
matrix:
  include:
    - gemfile: gemfiles/3.0
      rvm: 1.9.3
    - gemfile: gemfiles/3.1
      rvm: 1.9.3
    - gemfile: gemfiles/3.2
      rvm: 1.9.3
    - gemfile: gemfiles/3.3
      rvm: 1.9.3


    - gemfile: gemfiles/3.0
      rvm: 2.0.0
    - gemfile: gemfiles/3.1
      rvm: 2.0.0
    - gemfile: gemfiles/3.2
      rvm: 2.0.0
    - gemfile: gemfiles/3.3
      rvm: 2.0.0


    - gemfile: gemfiles/3.0
      rvm: 2.1.2
    - gemfile: gemfiles/3.1
      rvm: 2.1.2
    - gemfile: gemfiles/3.2
      rvm: 2.1.2
    - gemfile: gemfiles/3.3
      rvm: 2.1.2
